// Code generated by MockGen. DO NOT EDIT.
// Source: service.go
//
// Generated by this command:
//
//	mockgen -source=service.go -destination=mocks/mocks.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	time "time"

	models "github.com/ruslanonly/blindtyping/src/internal/models"
	statistics_repository "github.com/ruslanonly/blindtyping/src/internal/repositories/statistics_repository"
	user_repository "github.com/ruslanonly/blindtyping/src/internal/repositories/user_repository"
	gomock "go.uber.org/mock/gomock"
)

// MockstatisticsRepository is a mock of statisticsRepository interface.
type MockstatisticsRepository struct {
	ctrl     *gomock.Controller
	recorder *MockstatisticsRepositoryMockRecorder
	isgomock struct{}
}

// MockstatisticsRepositoryMockRecorder is the mock recorder for MockstatisticsRepository.
type MockstatisticsRepositoryMockRecorder struct {
	mock *MockstatisticsRepository
}

// NewMockstatisticsRepository creates a new mock instance.
func NewMockstatisticsRepository(ctrl *gomock.Controller) *MockstatisticsRepository {
	mock := &MockstatisticsRepository{ctrl: ctrl}
	mock.recorder = &MockstatisticsRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockstatisticsRepository) EXPECT() *MockstatisticsRepositoryMockRecorder {
	return m.recorder
}

// DeleteAllByUserID mocks base method.
func (m *MockstatisticsRepository) DeleteAllByUserID(ctx context.Context, userID models.ID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteAllByUserID", ctx, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteAllByUserID indicates an expected call of DeleteAllByUserID.
func (mr *MockstatisticsRepositoryMockRecorder) DeleteAllByUserID(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteAllByUserID", reflect.TypeOf((*MockstatisticsRepository)(nil).DeleteAllByUserID), ctx, userID)
}

// Exists mocks base method.
func (m *MockstatisticsRepository) Exists(ctx context.Context, idempotencyKey string) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Exists", ctx, idempotencyKey)
	ret0, _ := ret[0].(bool)
	return ret0
}

// Exists indicates an expected call of Exists.
func (mr *MockstatisticsRepositoryMockRecorder) Exists(ctx, idempotencyKey any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Exists", reflect.TypeOf((*MockstatisticsRepository)(nil).Exists), ctx, idempotencyKey)
}

// Get mocks base method.
func (m *MockstatisticsRepository) Get(ctx context.Context, in *statistics_repository.GetIn) ([]models.Statistics, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, in)
	ret0, _ := ret[0].([]models.Statistics)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockstatisticsRepositoryMockRecorder) Get(ctx, in any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockstatisticsRepository)(nil).Get), ctx, in)
}

// Save mocks base method.
func (m *MockstatisticsRepository) Save(ctx context.Context, stats *models.Statistics) (*models.Statistics, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", ctx, stats)
	ret0, _ := ret[0].(*models.Statistics)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Save indicates an expected call of Save.
func (mr *MockstatisticsRepositoryMockRecorder) Save(ctx, stats any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockstatisticsRepository)(nil).Save), ctx, stats)
}

// MockuserRepository is a mock of userRepository interface.
type MockuserRepository struct {
	ctrl     *gomock.Controller
	recorder *MockuserRepositoryMockRecorder
	isgomock struct{}
}

// MockuserRepositoryMockRecorder is the mock recorder for MockuserRepository.
type MockuserRepositoryMockRecorder struct {
	mock *MockuserRepository
}

// NewMockuserRepository creates a new mock instance.
func NewMockuserRepository(ctrl *gomock.Controller) *MockuserRepository {
	mock := &MockuserRepository{ctrl: ctrl}
	mock.recorder = &MockuserRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockuserRepository) EXPECT() *MockuserRepositoryMockRecorder {
	return m.recorder
}

// GetOne mocks base method.
func (m *MockuserRepository) GetOne(ctx context.Context, in *user_repository.GetOneIn) (*models.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOne", ctx, in)
	ret0, _ := ret[0].(*models.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOne indicates an expected call of GetOne.
func (mr *MockuserRepositoryMockRecorder) GetOne(ctx, in any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOne", reflect.TypeOf((*MockuserRepository)(nil).GetOne), ctx, in)
}

// MocklanguageRepository is a mock of languageRepository interface.
type MocklanguageRepository struct {
	ctrl     *gomock.Controller
	recorder *MocklanguageRepositoryMockRecorder
	isgomock struct{}
}

// MocklanguageRepositoryMockRecorder is the mock recorder for MocklanguageRepository.
type MocklanguageRepositoryMockRecorder struct {
	mock *MocklanguageRepository
}

// NewMocklanguageRepository creates a new mock instance.
func NewMocklanguageRepository(ctrl *gomock.Controller) *MocklanguageRepository {
	mock := &MocklanguageRepository{ctrl: ctrl}
	mock.recorder = &MocklanguageRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MocklanguageRepository) EXPECT() *MocklanguageRepositoryMockRecorder {
	return m.recorder
}

// Get mocks base method.
func (m *MocklanguageRepository) Get() models.Languages {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get")
	ret0, _ := ret[0].(models.Languages)
	return ret0
}

// Get indicates an expected call of Get.
func (mr *MocklanguageRepositoryMockRecorder) Get() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MocklanguageRepository)(nil).Get))
}

// Mockantifroad is a mock of antifroad interface.
type Mockantifroad struct {
	ctrl     *gomock.Controller
	recorder *MockantifroadMockRecorder
	isgomock struct{}
}

// MockantifroadMockRecorder is the mock recorder for Mockantifroad.
type MockantifroadMockRecorder struct {
	mock *Mockantifroad
}

// NewMockantifroad creates a new mock instance.
func NewMockantifroad(ctrl *gomock.Controller) *Mockantifroad {
	mock := &Mockantifroad{ctrl: ctrl}
	mock.recorder = &MockantifroadMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *Mockantifroad) EXPECT() *MockantifroadMockRecorder {
	return m.recorder
}

// IsFroad mocks base method.
func (m *Mockantifroad) IsFroad(payload models.SignPayload, sign string) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsFroad", payload, sign)
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsFroad indicates an expected call of IsFroad.
func (mr *MockantifroadMockRecorder) IsFroad(payload, sign any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsFroad", reflect.TypeOf((*Mockantifroad)(nil).IsFroad), payload, sign)
}

// MockpbService is a mock of pbService interface.
type MockpbService struct {
	ctrl     *gomock.Controller
	recorder *MockpbServiceMockRecorder
	isgomock struct{}
}

// MockpbServiceMockRecorder is the mock recorder for MockpbService.
type MockpbServiceMockRecorder struct {
	mock *MockpbService
}

// NewMockpbService creates a new mock instance.
func NewMockpbService(ctrl *gomock.Controller) *MockpbService {
	mock := &MockpbService{ctrl: ctrl}
	mock.recorder = &MockpbServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockpbService) EXPECT() *MockpbServiceMockRecorder {
	return m.recorder
}

// IsPB mocks base method.
func (m *MockpbService) IsPB(ctx context.Context, stats *models.Statistics) (bool, float64) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsPB", ctx, stats)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(float64)
	return ret0, ret1
}

// IsPB indicates an expected call of IsPB.
func (mr *MockpbServiceMockRecorder) IsPB(ctx, stats any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsPB", reflect.TypeOf((*MockpbService)(nil).IsPB), ctx, stats)
}

// MockleaderboardService is a mock of leaderboardService interface.
type MockleaderboardService struct {
	ctrl     *gomock.Controller
	recorder *MockleaderboardServiceMockRecorder
	isgomock struct{}
}

// MockleaderboardServiceMockRecorder is the mock recorder for MockleaderboardService.
type MockleaderboardServiceMockRecorder struct {
	mock *MockleaderboardService
}

// NewMockleaderboardService creates a new mock instance.
func NewMockleaderboardService(ctrl *gomock.Controller) *MockleaderboardService {
	mock := &MockleaderboardService{ctrl: ctrl}
	mock.recorder = &MockleaderboardServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockleaderboardService) EXPECT() *MockleaderboardServiceMockRecorder {
	return m.recorder
}

// UpdateRank mocks base method.
func (m *MockleaderboardService) UpdateRank(ctx context.Context, userID models.ID, language models.Language, mode models.Mode, submode models.Submode, wpm float64, accuracy float64, playedAt time.Time) (*models.RankChange, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateRank", ctx, userID, language, mode, submode, wpm, accuracy, playedAt)
	ret0, _ := ret[0].(*models.RankChange)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateRank indicates an expected call of UpdateRank.
func (mr *MockleaderboardServiceMockRecorder) UpdateRank(ctx, userID, language, mode, submode, wpm, accuracy, playedAt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateRank", reflect.TypeOf((*MockleaderboardService)(nil).UpdateRank), ctx, userID, language, mode, submode, wpm, accuracy, playedAt)
}
